$p = 'server\finance\routes.ts'

$lines = [System.Collections.Generic.List[string]](Get-Content $p)

$markerIndex = $lines.FindIndex({
    param($line)
    $line -eq '// COMPANY EXPENSES'
})

if ($markerIndex -lt 0) {
    throw 'COMPANY EXPENSES marker not found'
}

$block = @(
    ''
    '// ============================================================'
    '// COMPANY TRANSACTIONS'
    '// ============================================================'
    ''
    "router.post('/company/transactions', async (req, res) => {"
    '  try {'
    '    const workspaceId = workspaceIdFromRequest(req)'
    ''
    '    const { userId } ='
    '      await requireCompanyFinanceAccess('
    '        req,'
    '        workspaceId,'
    '      )'
    ''
    "    const accountId = String(req.body.accountId || '').trim()"
    ''
    '    if (!accountId) {'
    "      throw new Error('accountId is required')"
    '    }'
    ''
    "    const amount = money(req.body.amount, 'amount')"
    "    const transactionType = requiredText(req.body.transactionType, 'transactionType')"
    ''
    "    if (!['income', 'adjustment'].includes(transactionType)) {"
    "      throw new Error('Invalid company transaction type')"
    '    }'
    ''
    "    const description = requiredText(req.body.description, 'description')"
    ''
    '    const transactionDate ='
    '      req.body.transactionDate'
    '        ? String(req.body.transactionDate)'
    '        : new Date().toISOString().slice(0, 10)'
    ''
    '    const category ='
    '      req.body.category'
    '        ? String(req.body.category)'
    '        : null'
    ''
    '    const reference ='
    '      req.body.reference'
    '        ? String(req.body.reference)'
    '        : null'
    ''
    '    const projectId ='
    '      req.body.projectId'
    '        ? String(req.body.projectId)'
    '        : null'
    ''
    '    const clientId ='
    '      req.body.clientId'
    '        ? String(req.body.clientId)'
    '        : null'
    ''
    '    const result ='
    '      await db.transaction(async (tx: any) => {'
    '        const [account] ='
    '          await tx'
    '            .select()'
    '            .from(companyFinanceAccounts)'
    '            .where('
    '              and('
    '                eq('
    '                  companyFinanceAccounts.id,'
    '                  accountId,'
    '                ),'
    '                eq('
    '                  companyFinanceAccounts.workspaceId,'
    '                  workspaceId,'
    '                ),'
    '              ),'
    '            )'
    '            .limit(1)'
    ''
    '        if (!account) {'
    "          throw new Error('Company finance account not found')"
    '        }'
    ''
    '        const [transaction] ='
    '          await tx'
    '            .insert(financeTransactions)'
    '            .values({'
    '              workspaceId,'
    '              accountId,'
    '              transactionType,'
    '              category,'
    '              description,'
    '              amount,'
    '              transactionDate,'
    '              reference,'
    '              projectId,'
    '              clientId,'
    '              createdByUserId: userId,'
    "              status: 'posted',"
    '              metadata: {},'
    '            })'
    '            .returning()'
    ''
    "        if (transactionType === 'income') {"
    '          await tx'
    '            .update(companyFinanceAccounts)'
    '            .set({'
    '              currentBalance:'
    '                String('
    '                  Number(account.currentBalance) +'
    '                    Number(amount),'
    '                ),'
    '            })'
    '            .where('
    '              and('
    '                eq('
    '                  companyFinanceAccounts.id,'
    '                  accountId,'
    '                ),'
    '                eq('
    '                  companyFinanceAccounts.workspaceId,'
    '                  workspaceId,'
    '                ),'
    '              ),'
    '            )'
    '        }'
    ''
    '        return transaction'
    '      })'
    ''
    '    res.status(201).json(result)'
    '  } catch (error) {'
    '    handleRouteError(res, error)'
    '  }'
    '})'
    ''
)

$lines.InsertRange($markerIndex, [string[]]$block)

[System.IO.File]::WriteAllLines($p, $lines)