import { useState } from 'react'
import { BriefcaseBusiness, Check, ChevronDown, ClipboardCheck, DollarSign, ShieldCheck, UsersRound } from 'lucide-react'

type PortalId = 'services' | 'sales' | 'hr' | 'team-lead' | 'finance'

const portals: { id: PortalId; label: string; description: string; icon: typeof BriefcaseBusiness }[] = [
  { id: 'services', label: 'Services employee portal', description: 'Projects, tasks, RFIs, estimates', icon: BriefcaseBusiness },
  { id: 'sales', label: 'Sales employee portal', description: 'Leads, clients, calls, pipeline', icon: UsersRound },
  { id: 'hr', label: 'HR portal', description: 'People, leave, attendance', icon: ShieldCheck },
  { id: 'team-lead', label: 'Team lead portal', description: 'Team workload and approvals', icon: ClipboardCheck },
  { id: 'finance', label: 'Finance employee portal', description: 'Expenses, payments, balances', icon: DollarSign },
]

function DepartmentPlaceholder({ portal }: { portal: typeof portals[number] }) {
  const Icon = portal.icon
  return <div className="min-h-full bg-[#080d18] p-4 text-[#dae2fd] md:p-7"><div className="mx-auto max-w-[1400px] space-y-6"><header className="border-b border-[#222a3d] pb-5"><p className="text-[10px] font-mono uppercase tracking-[0.24em] text-[#4edea3]">Employee operations / {portal.id}</p><h1 className="mt-2 text-2xl font-semibold text-white">{portal.label}</h1><p className="mt-1 text-sm text-[#86948a]">{portal.description}. This workspace follows the same services employee layout and permission model.</p></header><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{['Today', 'Open work', 'Pending approvals', 'Attendance'].map((label, index) => <div key={label} className="rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4"><p className="text-2xl font-semibold text-white">{index === 0 ? '09:00' : index === 1 ? '08' : index === 2 ? '03' : 'Present'}</p><p className="mt-1 text-xs text-[#bbcabf]">{label}</p><p className="mt-2 text-[10px] font-mono text-[#4edea3]">Updated just now</p></div>)}</section><div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><section className="rounded-2xl border border-[#222a3d] bg-[#0d1728] p-5"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-[#4edea3]" /><h2 className="text-lg font-semibold text-white">{portal.label} workspace</h2></div><div className="mt-4 space-y-2">{['Review today’s assignments', 'Update status and next action', 'Submit required documentation'].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl bg-[#0a1220] p-3 text-xs text-[#bbcabf]"><span className="flex h-5 w-5 items-center justify-center rounded-full border border-[#2b3851]"><Check className="h-3 w-3 text-[#4edea3]" /></span>{item}</div>)}</div></section><section className="rounded-2xl border border-[#222a3d] bg-[#0d1728] p-5"><p className="text-[10px] font-mono uppercase tracking-wider text-[#86948a]">Visibility</p><h2 className="mt-1 text-lg font-semibold text-white">Leadership view</h2><p className="mt-2 text-xs leading-5 text-[#86948a]">Team leads and founders can see activity, ownership, progress, and approvals according to assigned permissions.</p></section></div></div></div>
}

export function EmployeePortalHub() {
  const [portal, setPortal] = useState<PortalId>('services')
  const [open, setOpen] = useState(false)
  const [permissions, setPermissions] = useState<Record<PortalId, boolean>>({ services: true, sales: true, hr: false, 'team-lead': false, finance: false })
  const selected = portals.find((item) => item.id === portal) ?? portals[0]
  const SelectedIcon = selected.icon
  return <div className="relative min-h-full"><div className="sticky top-0 z-30 border-b border-[#222a3d] bg-[#080d18]/95 px-4 py-3 backdrop-blur md:px-7"><div className="mx-auto flex max-w-[1400px] flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-mono uppercase tracking-[0.22em] text-[#4edea3]">Portal directory</p><p className="mt-1 text-xs text-[#86948a]">Choose a workspace and manage who can access it.</p></div><div className="flex items-center gap-2"><div className="relative"><button type="button" onClick={() => setOpen((value) => !value)} className="flex min-w-[270px] items-center justify-between gap-4 rounded-xl border border-[#4edea3]/30 bg-[#0d1728] px-3 py-2 text-left"><span className="flex items-center gap-2"><SelectedIcon className="h-4 w-4 text-[#4edea3]" /><span><span className="block text-xs font-semibold text-white">{selected.label}</span><span className="block text-[10px] text-[#86948a]">{selected.description}</span></span></span><ChevronDown className="h-4 w-4 text-[#86948a]" /></button>{open && <div className="absolute right-0 top-full mt-2 w-[320px] rounded-xl border border-[#2b3851] bg-[#0d1728] p-2 shadow-2xl">{portals.map((item) => { const Icon = item.icon; return <button key={item.id} type="button" onClick={() => { setPortal(item.id); setOpen(false) }} className={`flex w-full items-center gap-3 rounded-lg p-3 text-left ${portal === item.id ? 'bg-[#4edea3]/10' : 'hover:bg-[#131b2e]'}`}><Icon className="h-4 w-4 text-[#4edea3]" /><span><span className="block text-xs font-semibold text-white">{item.label}</span><span className="block text-[10px] text-[#86948a]">{item.description}</span></span></button> })}</div>}</div><button type="button" onClick={() => setOpen((value) => !value)} className="rounded-xl border border-[#2b3851] px-3 py-2 text-xs font-semibold text-[#7db2ff]">Permissions</button></div></div>{open && <div className="mx-auto mt-3 max-w-[1400px] rounded-xl border border-[#7db2ff]/20 bg-[#0d1728] p-3"><p className="text-[10px] font-mono uppercase tracking-wider text-[#7db2ff]">Portal permissions</p><div className="mt-2 flex flex-wrap gap-2">{portals.map((item) => <label key={item.id} className="flex items-center gap-2 rounded-lg bg-[#0a1220] px-3 py-2 text-[10px] text-[#bbcabf]"><input type="checkbox" checked={permissions[item.id]} onChange={(event) => setPermissions((current) => ({ ...current, [item.id]: event.target.checked }))} className="accent-[#4edea3]" />{item.label}</label>)}</div></div>}</div><DepartmentPlaceholder portal={selected} /></div>
}

export default EmployeePortalHub
