import { useMemo, useState } from 'react'
import { CalendarClock, CheckCircle2, Clock3, DollarSign, Phone, Plus, Target, UserPlus, Users, X } from 'lucide-react'

type Lead = { id: string; company: string; client: string; scope: string; stage: string; temperature: string; value: number; nextCall: string; owner: string }

const initialLeads: Lead[] = [
  { id: 'lead-1', company: 'Northstar Builders', client: 'Avery Brooks', scope: 'Commercial estimating and takeoff services', stage: 'Qualified', temperature: 'Hot', value: 185000, nextCall: 'Today · 10:30 AM', owner: 'Maya Chen' },
  { id: 'lead-2', company: 'Lumen Architecture Group', client: 'Jordan Patel', scope: 'BIM coordination and shop drawing review', stage: 'Discovery', temperature: 'Warm', value: 92000, nextCall: 'Tomorrow · 2:00 PM', owner: 'Maya Chen' },
  { id: 'lead-3', company: 'CivicWorks Development', client: 'Sam Rivera', scope: 'Preconstruction cost planning', stage: 'Proposal', temperature: 'Warm', value: 240000, nextCall: 'Sep 24 · 9:00 AM', owner: 'Maya Chen' },
]

const stageStyles: Record<string, string> = { New: 'bg-[#7db2ff]/10 text-[#9bc3ff]', Discovery: 'bg-[#c084fc]/10 text-[#d8aaff]', Qualified: 'bg-[#f0b44d]/10 text-[#f5c76e]', Proposal: 'bg-[#4edea3]/10 text-[#6ee7b7]', Won: 'bg-[#4edea3]/20 text-[#8ff0bf]' }

export function SalesEmployeePortal() {
  const [leads, setLeads] = useState(initialLeads)
  const [showRegistration, setShowRegistration] = useState(false)
  const [notice, setNotice] = useState('')
  const [clockedIn, setClockedIn] = useState(false)
  const [form, setForm] = useState({ company: '', client: '', description: '', scope: '', value: '' })
  const totalPipeline = useMemo(() => leads.reduce((sum, lead) => sum + lead.value, 0), [leads])
  const submitLead = () => {
    if (!form.company || !form.client || !form.scope) return
    setLeads((current) => [{ id: `lead-${Date.now()}`, company: form.company, client: form.client, scope: form.scope, stage: 'New', temperature: 'Warm', value: Number(form.value) || 0, nextCall: 'Set follow-up', owner: 'Maya Chen' }, ...current])
    setForm({ company: '', client: '', description: '', scope: '', value: '' })
    setShowRegistration(false)
    setNotice('Client lead registered and assigned to you.')
  }
  return <div className="min-h-full bg-[#080d18] text-[#dae2fd]">
    <div className="mx-auto max-w-[1400px] space-y-6 p-4 md:p-7">
      <header className="flex flex-col gap-4 border-b border-[#222a3d] pb-5 lg:flex-row lg:items-end lg:justify-between">
        <div><p className="text-[10px] font-mono uppercase tracking-[0.24em] text-[#4edea3]">Sales operations / employee portal</p><h1 className="mt-2 text-2xl font-semibold text-white">Good morning, Maya.</h1><p className="mt-1 text-sm text-[#86948a]">Own your leads, protect your follow-ups, and keep leadership aligned.</p></div>
        <button type="button" onClick={() => { setClockedIn((value) => !value); setNotice(clockedIn ? 'Clocked out for today.' : 'Attendance clocked in for today.') }} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-bold ${clockedIn ? 'bg-[#4edea3] text-[#07101f]' : 'border border-[#4edea3]/30 bg-[#4edea3]/10 text-[#6ee7b7]'}`}><Clock3 className="h-4 w-4" />{clockedIn ? 'Clock out' : 'Clock in'}<span className="font-mono opacity-70">{clockedIn ? 'Active' : '09:00 AM'}</span></button>
      </header>
      {notice && <div className="rounded-xl border border-[#4edea3]/30 bg-[#4edea3]/10 px-4 py-3 text-xs text-[#8ff0bf]">{notice}</div>}
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[leads.length.toString(), 'My active leads', '3 need next action'], [`$${Math.round(totalPipeline / 1000)}k`, 'Pipeline value', 'Owned by you'], ['04', 'Calls this week', '1 due today'], ['92%', 'Follow-up health', 'Above team target']].map(([value, label, note]) => <div key={label} className="rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4"><p className="text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-[#bbcabf]">{label}</p><p className="mt-2 text-[10px] font-mono text-[#4edea3]">{note}</p></div>)}</section>
      <div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]">
        <section className="rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4 md:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-mono uppercase tracking-wider text-[#86948a]">Personal pipeline</p><h2 className="mt-1 text-lg font-semibold text-white">My leads and next actions</h2></div><button type="button" onClick={() => setShowRegistration(true)} className="inline-flex items-center gap-2 rounded-lg bg-[#4edea3] px-3 py-2 text-xs font-bold text-[#07101f]"><UserPlus className="h-3.5 w-3.5" />Register client</button></div><div className="mt-4 space-y-3">{leads.map((lead) => <article key={lead.id} className="rounded-xl border border-[#222a3d] bg-[#0a1220] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="text-sm font-semibold text-white">{lead.company}</h3><span className={`rounded-full px-2 py-0.5 text-[9px] font-bold ${stageStyles[lead.stage] || stageStyles.New}`}>{lead.stage}</span></div><p className="mt-1 text-xs text-[#bbcabf]">{lead.client} · {lead.scope}</p><p className="mt-2 text-[10px] text-[#86948a]">{lead.temperature} lead · Owner: {lead.owner}</p></div><p className="font-mono text-sm font-semibold text-[#6ee7b7]">${lead.value.toLocaleString()}</p></div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-[#222a3d] pt-3"><span className="inline-flex items-center gap-1.5 text-[10px] text-[#f0b44d]"><CalendarClock className="h-3.5 w-3.5" />Next call: {lead.nextCall}</span><div className="flex gap-2"><button type="button" onClick={() => setNotice(`Follow-up reminder set for ${lead.company}.`)} className="rounded-lg border border-[#2b3851] px-2.5 py-1.5 text-[10px] font-semibold text-[#7db2ff]">Set reminder</button><button type="button" onClick={() => setNotice(`Call logged for ${lead.company}.`)} className="inline-flex items-center gap-1 rounded-lg bg-[#4edea3]/10 px-2.5 py-1.5 text-[10px] font-semibold text-[#6ee7b7]"><Phone className="h-3 w-3" />Log call</button></div></div></article>)}</div></section>
        <aside className="space-y-6"><section className="rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4 md:p-5"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-[#f0b44d]" /><h2 className="text-sm font-semibold text-white">Today&apos;s sales actions</h2></div><div className="mt-4 space-y-3"><div className="rounded-xl bg-[#f0b44d]/10 p-3"><p className="text-xs font-semibold text-[#f5c76e]">Call Avery Brooks</p><p className="mt-1 text-[10px] text-[#d7c99d]">Northstar Builders · 10:30 AM</p></div><div className="rounded-xl bg-[#0a1220] p-3"><p className="text-xs font-semibold text-white">Send proposal follow-up</p><p className="mt-1 text-[10px] text-[#86948a]">CivicWorks Development · due today</p></div><div className="rounded-xl bg-[#0a1220] p-3"><p className="text-xs font-semibold text-white">Update lead qualification</p><p className="mt-1 text-[10px] text-[#86948a]">Lumen Architecture Group</p></div></div></section><section className="rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4 md:p-5"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-[#7db2ff]" /><h2 className="text-sm font-semibold text-white">Leadership visibility</h2></div><p className="mt-2 text-xs text-[#86948a]">Team leads and founders can see ownership, stage, value, and next activity without changing your assigned ownership.</p><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-lg bg-[#0a1220] p-3"><p className="text-lg font-semibold text-white">3</p><p className="text-[10px] text-[#86948a]">Owned leads</p></div><div className="rounded-lg bg-[#0a1220] p-3"><p className="text-lg font-semibold text-white">1</p><p className="text-[10px] text-[#86948a]">Proposal stage</p></div></div></section></aside>
      </div>
      {showRegistration && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#020611]/80 p-4" role="dialog" aria-modal="true"><form onSubmit={(event) => { event.preventDefault(); submitLead() }} className="w-full max-w-xl rounded-2xl border border-[#2b3851] bg-[#0d1728] p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-mono uppercase tracking-widest text-[#4edea3]">Sales CRM</p><h2 className="mt-1 text-lg font-semibold text-white">Register a new client lead</h2></div><button type="button" onClick={() => setShowRegistration(false)} aria-label="Close client registration"><X className="h-4 w-4 text-[#86948a]" /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['company', 'Company name'], ['client', 'Client name'], ['value', 'Estimated opportunity value']].map(([key, label]) => <label key={key} className="text-xs text-[#bbcabf]">{label}<input required={key !== 'value'} value={form[key as keyof typeof form]} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} className="mt-1.5 w-full rounded-lg border border-[#2b3851] bg-[#131b2e] px-3 py-2 text-xs text-white placeholder:text-[#667085]" placeholder={label} /></label>)}<label className="text-xs text-[#bbcabf] sm:col-span-2">What does the company do?<textarea value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} className="mt-1.5 min-h-20 w-full rounded-lg border border-[#2b3851] bg-[#131b2e] px-3 py-2 text-xs text-white" /></label><label className="text-xs text-[#bbcabf] sm:col-span-2">Scope of work / opportunity<textarea required value={form.scope} onChange={(event) => setForm((current) => ({ ...current, scope: event.target.value }))} className="mt-1.5 min-h-20 w-full rounded-lg border border-[#2b3851] bg-[#131b2e] px-3 py-2 text-xs text-white" /></label></div><button type="submit" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#4edea3] px-4 py-2 text-xs font-bold text-[#07101f]"><Plus className="h-3.5 w-3.5" />Save client lead</button></form></div>}
    </div>
  </div>
}

export default SalesEmployeePortal
